name: DevSecOps-CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

# Workflow-level concurrency to avoid overlapping runs for same ref
concurrency:
  group: devsecops-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: myapp
  ARTIFACT_NAME: app-jar

jobs:

  ##########################
  # CI: Build, Scan, Test  #
  ##########################
  ci_build_and_scan:
    name: CI — Build / SAST / SCA / SBOM / Container Scan
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-image.outputs.image }}
      artifact-path: ${{ steps.upload-artifact.outputs.artifact-path || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install CLI tools (trivy, syft, cosign)
        run: |
          # lightweight installs - change to pinned versions as needed
          sudo apt-get update
          sudo apt-get install -y curl unzip
          curl -sSfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sudo sh -s -- -b /usr/local/bin
          curl -sSfL https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -o /usr/local/bin/cosign && sudo chmod +x /usr/local/bin/cosign

      - name: Build (Maven) — CI
        id: build
        run: mvn -B -DskipTests package

      - name: Upload build artifact (jar) — CI
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: target/*.jar

      - name: SBOM generation (syft) — CI
        id: sbom
        run: |
          syft packages dir:. -o cyclonedx-json > sbom.cyclonedx.json
        continue-on-error: false

      - name: Static Analysis (CodeQL) — CI
        uses: github/codeql-action/init@v3
        with:
          languages: java
      - name: Run CodeQL — CI
        uses: github/codeql-action/analyze@v3

      - name: Semgrep quick scan — CI
        uses: returntocorp/semgrep-action@v2
        with:
          args: --config=p/ci

      - name: Dependency / SCA scan (Snyk) — CI
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Secret scan (Gitleaks) — CI
        uses: zricethezav/gitleaks-action@v2
        with:
          args: --path=.

      - name: Unit tests — CI
        run: mvn test -B

      - name: Build Docker image — CI
        uses: docker/build-push-action@v5
        id: docker_build
        with:
          context: .
          push: false
          tags: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Container vulnerability scan (Trivy) — CI
        run: |
          trivy image --exit-code 1 --severity CRITICAL,HIGH ${IMAGE_REGISTRY}/${IMAGE_NAME}:${{ github.sha }} || (echo "Vuln found"; exit 1)
        env:
          IMAGE_REGISTRY: ${{ env.IMAGE_REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}

      - name: Save image info for CD
        id: set-image
        run: echo "::set-output name=image::${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"

  ####################################################
  # CI: Publish Hardened Artifact to Registry (Repo) #
  ####################################################
  ci_publish:
    name: CI — Publish Artifact & Sign (push image + sign)
    runs-on: ubuntu-latest
    needs: ci_build_and_scan
    if: ${{ success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull built image locally (optional)
        run: docker pull ${{ needs.ci_build_and_scan.outputs.image }} || true

      - name: Tag & Push image — CI
        run: |
          docker tag ${{ needs.ci_build_and_scan.outputs.image }} ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:stable-${{ github.run_number }}
          docker push ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:stable-${{ github.run_number }}
        env:
          IMAGE_REGISTRY: ${{ env.IMAGE_REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}

      - name: Sign image with Cosign — CI
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          # assumes COSIGN_PRIVATE_KEY is stored as secret and written to file
          echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
          cosign sign --key cosign.key ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:stable-${{ github.run_number }}

      - name: Publish SBOM artifact — CI
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.cyclonedx.json

  ####################################################
  # CD: Pre-deploy checks + Staging Deploy (GitOps)  #
  ####################################################
  cd_deploy_staging:
    name: CD — Pre-deploy checks & Deploy to Staging
    runs-on: ubuntu-latest
    needs: ci_publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download SBOM — CD
        uses: actions/download-artifact@v4
        with:
          name: sbom
          path: ./sbom

      - name: Verify image signature — CD
        run: |
          echo "${{ secrets.COSIGN_PUBLIC_KEY }}" > cosign.pub
          cosign verify --key cosign.pub ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:stable-${{ github.run_number }}

      - name: IaC Policy-as-Code (Check with OPA/Kyverno) — CD
        run: |
          # Example: run kyverno CLI or kubectl apply --dry-run=server for policies
          echo "Run policy checks (Kyverno/OPA) against manifests"

      - name: Inject secrets from Vault (fetch staging creds) — CD
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        run: |
          echo "Fetch secrets via Vault OIDC or GitHub OIDC -> Vault role"
          # Placeholder: use hashicorp/vault-action or vault CLI

      - name: Deploy to Staging (ArgoCD / kubectl) — CD
        env:
          IMAGE_TAG: stable-${{ github.run_number }}
        run: |
          # Example GitOps trigger: update image tag in Git repo or call ArgoCD API
          echo "Trigger ArgoCD / apply manifests for staging with image $IMAGE_TAG"

  ####################################################
  # CD: Production Deploy (Gated)                    #
  ####################################################
  cd_deploy_production:
    name: CD — Production Deploy (Manual approval / Environment)
    runs-on: ubuntu-latest
    needs: cd_deploy_staging
    environment:
      name: production
      url: https://myapp.example.com
    # Require environment protection rules in GitHub to force approval
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify image signature (again) — CD
        run: |
          echo "${{ secrets.COSIGN_PUBLIC_KEY }}" > cosign.pub
          cosign verify --key cosign.pub ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:stable-${{ github.run_number }}

      - name: Final policy gating (OPA/Gatekeeper) — CD
        run: |
          echo "Run final gating policies (deny if resource limits missing / root containers / image not allowed)"

      - name: Deploy to Production (ArgoCD / GitOps flow) — CD
        run: |
          echo "Trigger ArgoCD sync for production (only allowed after environment approval)"

      - name: Post-deploy checks — CD
        run: |
          echo "Run smoke tests, health checks, and register deployment in inventory"
